name: Build and Deploy Docker Image

on:
  push:
    paths:
      - 'src/**'

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      app_ver: ${{ steps.step1.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: update app version
        id: step1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          OLD_VERSION: ${{ vars.APP_VERSION }}
        run: |
          IFS='.' read -r MAJOR MINOR <<< "${OLD_VERSION}"
          NEW_MAJOR=$((MAJOR + 1))
          NEW_VERSION="${NEW_MAJOR}.${MINOR}"
          gh variable set APP_VERSION --body "${NEW_VERSION}"
          echo "VERSION=${NEW_VERSION}" >> "$GITHUB_OUTPUT"
        
  debug:
    runs-on: ubuntu-latest
    needs: update
    env:
      app_ver: ${{needs.update.outputs.app_ver}}
    steps:
      - name: check github-env
        run: |
          echo $app_Ver
  # build:
  #   runs-on: ubuntu-latest
  #   env:
  #     APP_VERSION: ${{ vars.APP_VERSION }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_TOKEN }}

  #     - name: Set new value
  #       run: |
  #         gh variable set APP_VERSION --body "1.2.3"

  #     - name: Increment version number
  #       id: increment_version
  #       run: |
  #         NEW_VERSION=$((CURRENT_VERSION + 1))
  #         echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

  #     - name: Build Docker image
  #       run: |
  #         docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/simple-laravel:${NEW_VERSION} ./src

  #     - name: Push Docker image to Docker Hub
  #       run: |
  #         docker push ${{ secrets.DOCKER_HUB_USERNAME }}/simple-laravel:${NEW_VERSION}
  
  # release:
  #   runs-on: ubuntu-latest
  #   env:
  #     APP_VERSION: ${{ env.APP_VERSION }}
  #   steps:
  #     - name: Update version in manifest file
  #       run: |
  #         sed -i 's/\(image: .*:\)\([0-9]*\.[0-9]*\)/\1${NEW_VERSION}/' ./deploy/manifests/deployment.yaml

  #     - name: Commit and push changes
  #       run: |
  #         git config --local user.email "action@github.com"
  #         git config --local user.name "GitHub Action"
  #         git add ./deploy/manifests/deployment.yaml
  #         git commit -m "Update version to ${NEW_VERSION}"
  #         git push
