name: Build and Deploy Docker Image

on:
  push:
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Read current version from manifest
        id: read_version
        run: |
          CURRENT_VERSION=$(awk '/image: / {split($2, a, ":"); print a[2]}' ./deploy/manifests/deployment.yaml)
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Increment version number
        id: increment_version
        run: |
          NEW_VERSION=$((CURRENT_VERSION + 1))
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t hmd17/simple-laravel:${NEW_VERSION} ./src

      - name: Push Docker image to Docker Hub
        run: |
          docker push hmd17/simple-laravel:${NEW_VERSION}

      - name: Update version in manifest file
        run: |
          sed -i 's/\(image: .*:\)\([0-9]*\.[0-9]*\)/\1${NEW_VERSION}/' ./deploy/manifests/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./deploy/manifests/deployment.yaml
          git commit -m "Update version to ${NEW_VERSION}"
          git push
