name: Build and Deploy Docker Image

on:
  push:
    paths:
      - 'src/**'

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      app_ver: ${{ steps.step1.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: update app version
        id: step1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          OLD_VERSION: ${{ vars.APP_VERSION }}
        run: |
          IFS='.' read -r MAJOR MINOR <<< "${OLD_VERSION}"
          NEW_MAJOR=$((MAJOR + 1))
          NEW_VERSION="${NEW_MAJOR}.${MINOR}"
          gh variable set APP_VERSION --body "${NEW_VERSION}"
          echo "VERSION=${NEW_VERSION}" >> "$GITHUB_OUTPUT"
  
  build:
    runs-on: ubuntu-latest
    needs: update
    env:
      app_ver: ${{needs.update.outputs.app_ver}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/simple-laravel:$app_ver ./src

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/simple-laravel:$app_ver
  
  deploy:
    runs-on: ubuntu-latest
    needs: [update, build]
    env:
      app_ver: ${{needs.update.outputs.app_ver}}
    steps:
      - name: Update version in manifest file
        run: |
          sed -i 's/\(image: .*:\)\([0-9]*\.[0-9]*\)/\1$app_ver/' ./deploy/manifests/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./deploy/manifests/deployment.yaml
          git commit -m "Update version to $app_ver"
          git push
